/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (duke-nukem-time-to-kill-)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x800AB6FCu
#define func_800AB6FC BootEntry  /* alias */
